name: build

on: [push, pull_request]

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, pypy2, 3.5, 3.6, 3.7, 3.8, 3.9, pypy3]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r dev-requirements.in .

    - name: Lint
      if: matrix.python-version == 3.9
      run: |
        black --skip-string-normalization --check .
        flake8 --max-complexity 10 .

    - name: Test
      run: pytest -vx --cov=locks --cov-report term-missing --cov-fail-under 95

    - name: Upload coverage report to Codecov
      if: matrix.python-version == 3.9
      run: pip install codecov && codecov --slug=$GITHUB_REPOSITORY --branch=$GITHUB_REF --commit=$GITHUB_SHA
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: test
    if: startsWith(github.event.ref, 'refs/tags')

    name: Deploy Python package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check tag against package version
      run: grep '__version__' locks.py | grep -q "'${GITHUB_REF#refs/tags/}'"

    - name: Install dependencies
      run: pip install --upgrade setuptools twine wheel

    - name: Build distribution
      run: python setup.py sdist bdist_wheel

    - name: Publish artefacts
      run: twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
